"""empty message

Revision ID: 343325fbc120
Revises: a687ddb241d7
Create Date: 2018-10-21 11:24:06.943652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343325fbc120'
down_revision = 'a687ddb241d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_cart_ibfk_2', 'shop_cart', type_='foreignkey')
    op.create_foreign_key(None, 'shop_cart', 'product', ['pid'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_cart', type_='foreignkey')
    op.create_foreign_key('shop_cart_ibfk_2', 'shop_cart', 'product', ['pid'], ['id'])
    # ### end Alembic commands ###
