"""empty message

Revision ID: 396149044b00
Revises: b8260c731679
Create Date: 2018-10-20 18:32:38.367401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396149044b00'
down_revision = 'b8260c731679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('order_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'order_time')
    # ### end Alembic commands ###
