"""empty message

Revision ID: 6831d0445aff
Revises: a8b2455d71fb
Create Date: 2018-10-19 10:26:21.248876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6831d0445aff'
down_revision = 'a8b2455d71fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shop_time', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'shop_time')
    # ### end Alembic commands ###
