"""empty message

Revision ID: 6c542fcf9bf4
Revises: bf70119cb34d
Create Date: 2018-10-13 09:38:53.343671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c542fcf9bf4'
down_revision = 'bf70119cb34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'desc')
    # ### end Alembic commands ###
