"""empty message

Revision ID: 7d0a43ea77f0
Revises: 9ea454cf6c18
Create Date: 2018-10-13 13:46:59.908309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d0a43ea77f0'
down_revision = '9ea454cf6c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'love_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('love_user', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
