"""empty message

Revision ID: 89367bd96c7f
Revises: 343325fbc120
Create Date: 2018-10-21 11:30:03.497638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89367bd96c7f'
down_revision = '343325fbc120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_cart_ibfk_2', 'shop_cart', type_='foreignkey')
    op.create_foreign_key(None, 'shop_cart', 'product', ['pid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_cart', type_='foreignkey')
    op.create_foreign_key('shop_cart_ibfk_2', 'shop_cart', 'product', ['pid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
