"""empty message

Revision ID: 9ea454cf6c18
Revises: 6c542fcf9bf4
Create Date: 2018-10-13 09:40:27.948142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ea454cf6c18'
down_revision = '6c542fcf9bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('pDesc', sa.Text(), nullable=True))
    op.drop_column('product', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('desc', mysql.TEXT(), nullable=True))
    op.drop_column('product', 'pDesc')
    # ### end Alembic commands ###
