"""empty message

Revision ID: a687ddb241d7
Revises: 8f2a20055100
Create Date: 2018-10-21 06:50:21.450207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a687ddb241d7'
down_revision = '8f2a20055100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('csid', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'product', 'category_second', ['csid'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'csid')
    # ### end Alembic commands ###
