"""empty message

Revision ID: a8b2455d71fb
Revises: b4c583d62cd5
Create Date: 2018-10-16 07:59:37.823233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b2455d71fb'
down_revision = 'b4c583d62cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_pass', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_pass')
    # ### end Alembic commands ###
