"""empty message

Revision ID: b8260c731679
Revises: 16636c4ccbce
Create Date: 2018-10-19 11:54:27.374517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8260c731679'
down_revision = '16636c4ccbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('head_img', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'head_img')
    # ### end Alembic commands ###
