"""empty message

Revision ID: bca6cd934ce2
Revises: e7a8ca1282fb
Create Date: 2018-10-13 17:52:21.242111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca6cd934ce2'
down_revision = 'e7a8ca1282fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('pid', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'comment', 'product', ['pid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'pid')
    # ### end Alembic commands ###
