"""empty message

Revision ID: c99da400bde4
Revises: 6831d0445aff
Create Date: 2018-10-19 10:31:24.447068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99da400bde4'
down_revision = '6831d0445aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shop_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'shop_time')
    # ### end Alembic commands ###
