"""empty message

Revision ID: e7a8ca1282fb
Revises: 7d0a43ea77f0
Create Date: 2018-10-13 13:47:27.861504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a8ca1282fb'
down_revision = '7d0a43ea77f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('love_user', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'love_user')
    # ### end Alembic commands ###
